name: 'dbt'
version: '1.0'
profile: 'default'

models:
  dbt:
    staging:
      +materialized: view
      +schema: silver
      +tags: ['staging']
    marts:
      core:
        +materialized: incremental
        +schema: gold   # make marts incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
        +tags: ['gold']
