name: my_data_pipeline_project
version: 1.0.0
profile: default

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
  - "target"

models:
  my_data_pipeline_project:
    materialized: view

seeds:
  my_data_pipeline_project:
    materialized: table

snapshots:
  my_data_pipeline_project:
    target: snapshot

tests:
  my_data_pipeline_project:
    target: test

# Additional configurations can be added as needed.